
import React, { useState, useEffect } from 'react';
import { ChevronLeft, Download, Undo, Redo, Layers, Maximize2, Sparkles, CheckCircle2, Loader2 } from 'lucide-react';
import { EVENT_TYPES, STYLES } from '../constants';
import { GeminiService } from '../services/geminiService';

interface WorkspacePageProps {
  onBack: () => void;
}

const WorkspacePage: React.FC<WorkspacePageProps> = ({ onBack }) => {
  const [eventType, setEventType] = useState(EVENT_TYPES[0]);
  const [prompt, setPrompt] = useState('');
  const [selectedStyle, setSelectedStyle] = useState(STYLES[0].id);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    const result = await GeminiService.generateInvitation({
      eventType,
      description: prompt || 'A beautiful, elegant celebration invitation',
      style: STYLES.find(s => s.id === selectedStyle)?.name || 'Minimalist'
    });
    
    if (result) {
      setGeneratedImage(result);
    }
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen bg-background-dark flex flex-col overflow-hidden">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-background-dark border-b border-[#3b3267]">
        <div className="flex items-center p-4 justify-between max-w-xl mx-auto w-full">
          <div className="flex items-center gap-4">
            <button onClick={onBack} className="p-1 hover:bg-white/10 rounded-full transition-colors">
              <ChevronLeft size={24} />
            </button>
            <h2 className="text-lg font-bold tracking-tight">AI Workspace</h2>
          </div>
          <button 
            disabled={!generatedImage}
            className="bg-primary disabled:opacity-50 disabled:cursor-not-allowed text-white px-4 py-1.5 rounded-full text-sm font-bold hover:bg-primary/90 transition-colors flex items-center gap-2"
          >
            <Download size={16} /> Download
          </button>
        </div>
      </header>

      <main className="flex-1 w-full max-w-xl mx-auto overflow-y-auto pb-32 no-scrollbar">
        {/* Toolbar */}
        <div className="flex justify-between items-center px-4 py-3 bg-white/5 backdrop-blur-md">
          <div className="flex gap-2">
            <button className="p-2 hover:bg-white/10 rounded-lg transition-colors"><Undo size={18} /></button>
            <button className="p-2 hover:bg-white/10 rounded-lg transition-colors"><Redo size={18} /></button>
            <button className="p-2 hover:bg-white/10 rounded-lg transition-colors"><Layers size={18} /></button>
          </div>
          <div className="text-xs font-medium text-gray-400">Draft saved just now</div>
        </div>

        {/* Preview Area */}
        <div className="p-4">
          <div className="relative group">
            <div 
              className="relative aspect-[3/4] rounded-2xl overflow-hidden bg-[#1a1630] border border-[#3b3267] shadow-2xl flex items-center justify-center"
            >
              {isGenerating ? (
                <div className="flex flex-col items-center gap-4 animate-pulse">
                  <Loader2 className="animate-spin text-primary" size={48} />
                  <p className="text-sm font-medium text-slate-400">Painting your vision...</p>
                </div>
              ) : generatedImage ? (
                <img 
                  src={generatedImage} 
                  alt="Generated Invitation" 
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="p-8 text-center space-y-4">
                  <div className="w-16 h-16 bg-white/5 rounded-full flex items-center justify-center mx-auto">
                    <Sparkles className="text-primary/50" size={32} />
                  </div>
                  <p className="text-slate-400 text-sm italic">Enter your configuration below to see the magic</p>
                </div>
              )}

              {/* Gradient Overlay for Text */}
              {generatedImage && (
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex flex-col justify-end p-8 text-center pointer-events-none">
                  <p className="text-white/80 uppercase tracking-[0.2em] text-xs mb-2 font-medium">Join us for</p>
                  <h1 className="text-white text-3xl font-bold mb-4">{eventType}</h1>
                  <div className="w-12 h-1 bg-primary mx-auto rounded-full mb-4"></div>
                  <p className="text-white/40 text-[10px] italic">Generated by InviteAI</p>
                </div>
              )}
            </div>

            <button className="absolute top-4 right-4 p-2 bg-black/40 backdrop-blur-md text-white rounded-full hover:bg-black/60 transition-colors">
              <Maximize2 size={20} />
            </button>
          </div>
        </div>

        {/* Controls */}
        <div className="mt-4 bg-background-editor rounded-t-[32px] pt-8 shadow-2xl space-y-8">
          <h3 className="text-xl font-bold px-6">Configure Invitation</h3>
          
          {/* Event Type */}
          <div className="px-6 space-y-3">
            <label className="text-sm font-semibold text-gray-300">Event Type</label>
            <select 
              value={eventType}
              onChange={(e) => setEventType(e.target.value)}
              className="w-full h-14 bg-[#141122] border border-[#3b3267] rounded-xl px-4 text-white focus:ring-2 focus:ring-primary focus:border-transparent outline-none transition-all appearance-none cursor-pointer"
            >
              {EVENT_TYPES.map(type => (
                <option key={type} value={type}>{type}</option>
              ))}
            </select>
          </div>

          {/* Prompt */}
          <div className="px-6 space-y-3">
            <label className="text-sm font-semibold text-gray-300">AI Description Prompt</label>
            <textarea 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. A futuristic garden party with neon flowers and gold accents..."
              className="w-full min-h-[120px] bg-[#141122] border border-[#3b3267] rounded-xl p-4 text-white focus:ring-2 focus:ring-primary outline-none transition-all resize-none placeholder:text-gray-600"
            />
          </div>

          {/* Style Series */}
          <div className="space-y-4 pb-12">
            <div className="flex items-center justify-between px-6">
              <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Style Series</h4>
              <button className="text-xs text-primary font-bold">View All</button>
            </div>
            <div className="flex gap-4 overflow-x-auto px-6 no-scrollbar pb-2">
              {STYLES.map(style => (
                <button 
                  key={style.id}
                  onClick={() => setSelectedStyle(style.id)}
                  className="flex-shrink-0 w-24 group transition-transform active:scale-95"
                >
                  <div className={`aspect-square rounded-xl bg-gradient-to-br ${style.colorClass} border-2 relative overflow-hidden transition-all ${selectedStyle === style.id ? 'border-primary shadow-lg shadow-primary/20 scale-105' : 'border-transparent'}`}>
                    {selectedStyle === style.id && (
                      <div className="absolute inset-0 flex items-center justify-center bg-black/10 backdrop-blur-[1px]">
                        <CheckCircle2 className="text-primary fill-white" size={28} />
                      </div>
                    )}
                  </div>
                  <p className={`text-center mt-2 text-[10px] font-bold ${selectedStyle === style.id ? 'text-primary' : 'text-gray-400'}`}>
                    {style.name}
                  </p>
                </button>
              ))}
            </div>
          </div>
        </div>
      </main>

      {/* Footer Sticky Action */}
      <footer className="fixed bottom-0 left-0 right-0 p-4 bg-[#131022]/80 backdrop-blur-xl border-t border-[#3b3267] z-50">
        <div className="max-w-xl mx-auto">
          <button 
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full bg-primary hover:bg-primary/90 disabled:bg-primary/50 text-white font-bold py-4 rounded-2xl flex items-center justify-center gap-2 shadow-xl shadow-primary/20 transition-all active:scale-[0.98]"
          >
            {isGenerating ? (
              <Loader2 className="animate-spin" size={24} />
            ) : (
              <>
                <Sparkles size={20} />
                <span>{generatedImage ? 'Regenerate' : 'Generate Invitations'}</span>
              </>
            )}
          </button>
          <div className="mt-3 flex justify-center">
            <div className="w-24 h-1.5 bg-gray-800 rounded-full"></div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default WorkspacePage;
